//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input Action Maps/SpaceShip Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SpaceShipControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SpaceShipControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SpaceShip Controls"",
    ""maps"": [
        {
            ""name"": ""SpaceShip_Controls"",
            ""id"": ""ade88571-548b-4ca7-b5da-399cf2e957ad"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f9fc210d-11a9-4b96-a70f-3dc67d781a87"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Nitro"",
                    ""type"": ""Button"",
                    ""id"": ""f37bf19c-b21b-45d5-b7c1-e96d23f8866a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""cd941f8d-a722-4f23-9979-511b20099c5f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""ed29f896-3245-4639-b126-cb6cd7f2bbd0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HUD Switch"",
                    ""type"": ""Button"",
                    ""id"": ""e152a8c6-c46c-4b36-a71b-afafa59900a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation Lock"",
                    ""type"": ""Button"",
                    ""id"": ""586ae396-7f16-4616-8946-12ad096fc434"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Un Tether"",
                    ""type"": ""Button"",
                    ""id"": ""08bec861-269c-4b43-a481-cd2a4ebaadfa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Projectile Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""2a0f23fb-3397-4769-b0cf-8004946311ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throttle Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""30a55d92-04e2-46f2-a8da-2b7f54e70502"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Steering Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""56180f26-2fee-4e15-953e-778f2e330edd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Asteroid Camera"",
                    ""type"": ""Button"",
                    ""id"": ""6333d8e3-0bf2-4cd6-8435-f1e795c39652"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Steering Full Control Switch"",
                    ""type"": ""Button"",
                    ""id"": ""0e8463c1-31fa-4b80-aeb1-8056dd147636"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""1994c317-d2d1-440e-b177-1e2ec44a11a9"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""ffbfb516-5928-4fb4-bc63-7d565462f3d4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""da1bb8ce-132b-482d-80ab-88d5c7d5911b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""1328d097-cf7f-432f-a6a0-b9e440611c41"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""fe5dba6b-9e28-4898-b105-bdace5883813"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ba3e5abb-2832-4d0a-be6e-3e790c04e661"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bf56433-70f6-4a53-90a7-b904923b8667"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61fc2ae0-cf0f-410e-9e6c-19b0588659e1"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HUD Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d2662ce-b09a-43cf-9e8c-491363033fb3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ee7118a-15db-4361-ad99-d0ec3e067fd9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Projectile Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63f8e885-9c5e-4322-8f49-a2b17002ded7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Projectile Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4986d7dd-39c9-49a7-addb-49f14ab11cfc"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Un Tether"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""172bcbe7-4060-41fb-8298-00c2e016c50a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bbeb05c-f266-4e49-b310-d34d273a67d5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1005286-904a-4a7d-a5fc-7706c1af6390"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nitro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f640725-2ee3-451a-864c-ed3c10f0530a"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Asteroid Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e52a4c64-584d-469d-ab87-c3c2c105331f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6028b0b5-e834-4c2b-93bf-b2f76693735e"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering Full Control Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI Controls"",
            ""id"": ""60814cb8-5e43-4ae7-9eb4-32e4b819425e"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""cc00e2c1-1f8b-41da-8de8-bd62d90a1dca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4a95f89f-86ec-46bb-adfd-6b730b05ddc7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SpaceShip_Controls
        m_SpaceShip_Controls = asset.FindActionMap("SpaceShip_Controls", throwIfNotFound: true);
        m_SpaceShip_Controls_Movement = m_SpaceShip_Controls.FindAction("Movement", throwIfNotFound: true);
        m_SpaceShip_Controls_Nitro = m_SpaceShip_Controls.FindAction("Nitro", throwIfNotFound: true);
        m_SpaceShip_Controls_Aim = m_SpaceShip_Controls.FindAction("Aim", throwIfNotFound: true);
        m_SpaceShip_Controls_Shoot = m_SpaceShip_Controls.FindAction("Shoot", throwIfNotFound: true);
        m_SpaceShip_Controls_HUDSwitch = m_SpaceShip_Controls.FindAction("HUD Switch", throwIfNotFound: true);
        m_SpaceShip_Controls_RotationLock = m_SpaceShip_Controls.FindAction("Rotation Lock", throwIfNotFound: true);
        m_SpaceShip_Controls_UnTether = m_SpaceShip_Controls.FindAction("Un Tether", throwIfNotFound: true);
        m_SpaceShip_Controls_ProjectileWheel = m_SpaceShip_Controls.FindAction("Projectile Wheel", throwIfNotFound: true);
        m_SpaceShip_Controls_ThrottleWheel = m_SpaceShip_Controls.FindAction("Throttle Wheel", throwIfNotFound: true);
        m_SpaceShip_Controls_SteeringWheel = m_SpaceShip_Controls.FindAction("Steering Wheel", throwIfNotFound: true);
        m_SpaceShip_Controls_AsteroidCamera = m_SpaceShip_Controls.FindAction("Asteroid Camera", throwIfNotFound: true);
        m_SpaceShip_Controls_SteeringFullControlSwitch = m_SpaceShip_Controls.FindAction("Steering Full Control Switch", throwIfNotFound: true);
        // UI Controls
        m_UIControls = asset.FindActionMap("UI Controls", throwIfNotFound: true);
        m_UIControls_Pause = m_UIControls.FindAction("Pause", throwIfNotFound: true);
    }

    ~@SpaceShipControls()
    {
        UnityEngine.Debug.Assert(!m_SpaceShip_Controls.enabled, "This will cause a leak and performance issues, SpaceShipControls.SpaceShip_Controls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UIControls.enabled, "This will cause a leak and performance issues, SpaceShipControls.UIControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SpaceShip_Controls
    private readonly InputActionMap m_SpaceShip_Controls;
    private List<ISpaceShip_ControlsActions> m_SpaceShip_ControlsActionsCallbackInterfaces = new List<ISpaceShip_ControlsActions>();
    private readonly InputAction m_SpaceShip_Controls_Movement;
    private readonly InputAction m_SpaceShip_Controls_Nitro;
    private readonly InputAction m_SpaceShip_Controls_Aim;
    private readonly InputAction m_SpaceShip_Controls_Shoot;
    private readonly InputAction m_SpaceShip_Controls_HUDSwitch;
    private readonly InputAction m_SpaceShip_Controls_RotationLock;
    private readonly InputAction m_SpaceShip_Controls_UnTether;
    private readonly InputAction m_SpaceShip_Controls_ProjectileWheel;
    private readonly InputAction m_SpaceShip_Controls_ThrottleWheel;
    private readonly InputAction m_SpaceShip_Controls_SteeringWheel;
    private readonly InputAction m_SpaceShip_Controls_AsteroidCamera;
    private readonly InputAction m_SpaceShip_Controls_SteeringFullControlSwitch;
    public struct SpaceShip_ControlsActions
    {
        private @SpaceShipControls m_Wrapper;
        public SpaceShip_ControlsActions(@SpaceShipControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_SpaceShip_Controls_Movement;
        public InputAction @Nitro => m_Wrapper.m_SpaceShip_Controls_Nitro;
        public InputAction @Aim => m_Wrapper.m_SpaceShip_Controls_Aim;
        public InputAction @Shoot => m_Wrapper.m_SpaceShip_Controls_Shoot;
        public InputAction @HUDSwitch => m_Wrapper.m_SpaceShip_Controls_HUDSwitch;
        public InputAction @RotationLock => m_Wrapper.m_SpaceShip_Controls_RotationLock;
        public InputAction @UnTether => m_Wrapper.m_SpaceShip_Controls_UnTether;
        public InputAction @ProjectileWheel => m_Wrapper.m_SpaceShip_Controls_ProjectileWheel;
        public InputAction @ThrottleWheel => m_Wrapper.m_SpaceShip_Controls_ThrottleWheel;
        public InputAction @SteeringWheel => m_Wrapper.m_SpaceShip_Controls_SteeringWheel;
        public InputAction @AsteroidCamera => m_Wrapper.m_SpaceShip_Controls_AsteroidCamera;
        public InputAction @SteeringFullControlSwitch => m_Wrapper.m_SpaceShip_Controls_SteeringFullControlSwitch;
        public InputActionMap Get() { return m_Wrapper.m_SpaceShip_Controls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpaceShip_ControlsActions set) { return set.Get(); }
        public void AddCallbacks(ISpaceShip_ControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_SpaceShip_ControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpaceShip_ControlsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Nitro.started += instance.OnNitro;
            @Nitro.performed += instance.OnNitro;
            @Nitro.canceled += instance.OnNitro;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @HUDSwitch.started += instance.OnHUDSwitch;
            @HUDSwitch.performed += instance.OnHUDSwitch;
            @HUDSwitch.canceled += instance.OnHUDSwitch;
            @RotationLock.started += instance.OnRotationLock;
            @RotationLock.performed += instance.OnRotationLock;
            @RotationLock.canceled += instance.OnRotationLock;
            @UnTether.started += instance.OnUnTether;
            @UnTether.performed += instance.OnUnTether;
            @UnTether.canceled += instance.OnUnTether;
            @ProjectileWheel.started += instance.OnProjectileWheel;
            @ProjectileWheel.performed += instance.OnProjectileWheel;
            @ProjectileWheel.canceled += instance.OnProjectileWheel;
            @ThrottleWheel.started += instance.OnThrottleWheel;
            @ThrottleWheel.performed += instance.OnThrottleWheel;
            @ThrottleWheel.canceled += instance.OnThrottleWheel;
            @SteeringWheel.started += instance.OnSteeringWheel;
            @SteeringWheel.performed += instance.OnSteeringWheel;
            @SteeringWheel.canceled += instance.OnSteeringWheel;
            @AsteroidCamera.started += instance.OnAsteroidCamera;
            @AsteroidCamera.performed += instance.OnAsteroidCamera;
            @AsteroidCamera.canceled += instance.OnAsteroidCamera;
            @SteeringFullControlSwitch.started += instance.OnSteeringFullControlSwitch;
            @SteeringFullControlSwitch.performed += instance.OnSteeringFullControlSwitch;
            @SteeringFullControlSwitch.canceled += instance.OnSteeringFullControlSwitch;
        }

        private void UnregisterCallbacks(ISpaceShip_ControlsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Nitro.started -= instance.OnNitro;
            @Nitro.performed -= instance.OnNitro;
            @Nitro.canceled -= instance.OnNitro;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @HUDSwitch.started -= instance.OnHUDSwitch;
            @HUDSwitch.performed -= instance.OnHUDSwitch;
            @HUDSwitch.canceled -= instance.OnHUDSwitch;
            @RotationLock.started -= instance.OnRotationLock;
            @RotationLock.performed -= instance.OnRotationLock;
            @RotationLock.canceled -= instance.OnRotationLock;
            @UnTether.started -= instance.OnUnTether;
            @UnTether.performed -= instance.OnUnTether;
            @UnTether.canceled -= instance.OnUnTether;
            @ProjectileWheel.started -= instance.OnProjectileWheel;
            @ProjectileWheel.performed -= instance.OnProjectileWheel;
            @ProjectileWheel.canceled -= instance.OnProjectileWheel;
            @ThrottleWheel.started -= instance.OnThrottleWheel;
            @ThrottleWheel.performed -= instance.OnThrottleWheel;
            @ThrottleWheel.canceled -= instance.OnThrottleWheel;
            @SteeringWheel.started -= instance.OnSteeringWheel;
            @SteeringWheel.performed -= instance.OnSteeringWheel;
            @SteeringWheel.canceled -= instance.OnSteeringWheel;
            @AsteroidCamera.started -= instance.OnAsteroidCamera;
            @AsteroidCamera.performed -= instance.OnAsteroidCamera;
            @AsteroidCamera.canceled -= instance.OnAsteroidCamera;
            @SteeringFullControlSwitch.started -= instance.OnSteeringFullControlSwitch;
            @SteeringFullControlSwitch.performed -= instance.OnSteeringFullControlSwitch;
            @SteeringFullControlSwitch.canceled -= instance.OnSteeringFullControlSwitch;
        }

        public void RemoveCallbacks(ISpaceShip_ControlsActions instance)
        {
            if (m_Wrapper.m_SpaceShip_ControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpaceShip_ControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_SpaceShip_ControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpaceShip_ControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpaceShip_ControlsActions @SpaceShip_Controls => new SpaceShip_ControlsActions(this);

    // UI Controls
    private readonly InputActionMap m_UIControls;
    private List<IUIControlsActions> m_UIControlsActionsCallbackInterfaces = new List<IUIControlsActions>();
    private readonly InputAction m_UIControls_Pause;
    public struct UIControlsActions
    {
        private @SpaceShipControls m_Wrapper;
        public UIControlsActions(@SpaceShipControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_UIControls_Pause;
        public InputActionMap Get() { return m_Wrapper.m_UIControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIControlsActions set) { return set.Get(); }
        public void AddCallbacks(IUIControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_UIControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIControlsActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IUIControlsActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IUIControlsActions instance)
        {
            if (m_Wrapper.m_UIControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_UIControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIControlsActions @UIControls => new UIControlsActions(this);
    public interface ISpaceShip_ControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnNitro(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnHUDSwitch(InputAction.CallbackContext context);
        void OnRotationLock(InputAction.CallbackContext context);
        void OnUnTether(InputAction.CallbackContext context);
        void OnProjectileWheel(InputAction.CallbackContext context);
        void OnThrottleWheel(InputAction.CallbackContext context);
        void OnSteeringWheel(InputAction.CallbackContext context);
        void OnAsteroidCamera(InputAction.CallbackContext context);
        void OnSteeringFullControlSwitch(InputAction.CallbackContext context);
    }
    public interface IUIControlsActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
